// app/src/routes/register/+page.svelte
<script lang="ts">
  import supabase from "$lib/supabase";
  import { goto } from "$app/navigation";

  let email = "";
  let password = "";
  let error = "";
  let success = "";

  async function register() {
    error = "";
    success = "";

    const { error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      error = authError.message;
    } else {
      success = "Registration successful! Please check your email to confirm.";
    }
  }
</script>

<main class="p-6 max-w-md mx-auto">
  <h1 class="text-2xl font-bold mb-4">Register</h1>

  <form on:submit|preventDefault={register} class="space-y-4">
    <div>
      <label for="email">Email</label>
      <input
        name="email"
        type="email"
        bind:value={email}
        class="border w-full p-2 rounded text-black"
        required
      />
    </div>

    <div>
      <label for="password">Password</label>
      <input
        name="password"
        type="password"
        bind:value={password}
        class="border w-full p-2 rounded text-black"
        required
      />
    </div>

    {#if error}
      <p class="text-red-500">{error}</p>
    {/if}

    {#if success}
      <p class="text-green-500">{success}</p>
    {/if}

    <button type="submit" class="bg-sea text-black px-4 py-2 rounded">
      Register
    </button>
  </form>

  <p class="mt-4">
    Already have an account?
    <a href="/login" class="text-sea underline">Login</a>
  </p>
</main>

// src/app/(auth)/register/page.tsx
"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Image from "next/image"
import Link from "next/link"
import { toast } from "sonner"

import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export default function RegisterPage() {
  const router = useRouter()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [loading, setLoading] = useState(false)
  const [checkEmail, setCheckEmail] = useState(false)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)

    const supabase = createClient()
    const { error, data } = await supabase.auth.signUp({ email, password })

    if (error) {
      toast.error(error.message)
      setLoading(false)
      return
    }

    if (data.user && !data.session) {
      setCheckEmail(true)
      setLoading(false)
      return
    }

    router.push("/")
    router.refresh()
  }

  if (checkEmail) {
    return (
      <Card>
        <CardHeader className="space-y-2 text-center">
          <CardTitle className="text-2xl">Check your email</CardTitle>
          <CardDescription>
            We sent a confirmation link to <span className="text-foreground">{email}</span>. Click it to
            activate your account.
          </CardDescription>
        </CardHeader>
        <CardContent className="text-center">
          <Link href="/login" className="text-sm text-primary hover:underline">
            Back to sign in
          </Link>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader className="space-y-2 text-center">
        <Image
          src="/logomark-portico.svg"
          alt="Portico"
          width={40}
          height={40}
          className="mx-auto h-10 w-10"
          priority
        />
        <CardTitle className="text-2xl">Create an account</CardTitle>
        <CardDescription>Sign up to get started with Portico</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              placeholder="you@example.com"
              autoComplete="email"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={6}
              autoComplete="new-password"
            />
          </div>

          <Button type="submit" className="w-full" disabled={loading}>
            {loading ? "Creating account..." : "Sign up"}
          </Button>

          <p className="text-center text-sm text-muted-foreground">
            Already have an account?{" "}
            <Link href="/login" className="text-primary hover:underline">
              Sign in
            </Link>
          </p>
        </form>
      </CardContent>
    </Card>
  )
}
